### ISSUE TITLE
Crafting

### ISSUE THREAD

**Issue by JakeDaBoss** [JakeDaBoss/Pandemic#11]
- [ ] Recipes for guns. (Stock one can be found in hkusp)
- [ ] Junk items. (Check in Pandemic content for junk items.)

**Comment by JakeDaBoss** [comment]
Create gun parts and change the existing USP ones over to Pistol, don't forget the item unique id's.

Do this for SMG's, Shotguns, Snipers and Rifles.

I used a shitton of scanner gib models and I didn't find any gun part mods, so if you can find one that has those, bonus points for you.

**Comment by Zorxas** [comment]
I'll go ahead and take this one up.

**Comment by JakeDaBoss** [comment]
Crafting example set up in hkusp.
