### ISSUE TITLE
Code in item spawns

### ISSUE THREAD

**Issue by JakeDaBoss** [JakeDaBoss/Pandemic#12]
Item spawns (ugh) have to be configured.

- [ ] Properly set spawn chances and categories.
- [ ] Decide legendary spawns.

**Comment by JakeDaBoss** [comment]
Item spawn example is set in part_uspsight, last two lines before ITEM:REGISTER();

**Comment by JakeDaBoss** [comment]
Rare spawn is defined in Katana.

**Comment by WrongEnd** [comment]
Will work on this.
