### ISSUE TITLE
Weapon holstered locations are wrong.

### ISSUE THREAD

**Issue by JakeDaBoss** [JakeDaBoss/Pandemic#2]
They glitch.

**Comment by JakeDaBoss** [comment]
More in-depth information, they appear off-center and oftenly even completely turned sideways.

**Comment by SharpOB** [comment]
http://forums.cloudsixteen.com/threads/m9k-weapon-issues.13807/
Looking for a solution doesn't seem promising.

**Comment by SharpOB** [comment]
https://github.com/CloudSixteen/Clockwork/issues/145 <-- "Will Not Fix"
http://plugins.cloudsixteen.com/plugin/m9kironsightfix/view <-- Worth looking at, and may/may not fix it.
http://forums.cloudsixteen.com/threads/m9k.11389/ <-- Try this? Has ironsights and ammo. Will not work with above.

**Comment by JakeDaBoss** [comment]
@SharpOB the C16 issue was fixed with a plugin.

Lemme take al ook at this.
