### ISSUE TITLE
Check out all items files.

### ISSUE THREAD

**Issue by JakeDaBoss** [JakeDaBoss/Pandemic#25]
Check out for stuff like ITEM.classes = {EOW}, or someshit like that, and remove it.

**Comment by JakeDaBoss** [comment]
scratch that, ALL item files need checking.

**Comment by WrongEnd** [comment]
Assign me, please.

**Comment by SharpOB** [comment]
https://github.com/JakeDaBoss/Pandemic/pull/27

**Comment by JakeDaBoss** [comment]
For some odd reason I can't.
