### ISSUE TITLE
Weapon Items and ammo that still need creating

### ISSUE THREAD

**Issue by JakeDaBoss** [JakeDaBoss/Pandemic#5]
- [x] Pistols.
- [x] Assault Rifles.
- [x] Shotguns.
- [x] Specialties (?)
- [x] Snipers (?)
- [x] LMG's (?)

**Comment by SharpOB** [comment]
http://forums.cloudsixteen.com/threads/problems-with-m9k-weapon-packs.12173/

**Comment by SharpOB** [comment]
The solution I recommended in https://github.com/JakeDaBoss/Pandemic/issues/2 will have a byproduct of completing this.

**Comment by Zorxas** [comment]
I'll start on shotguns that have not yet been created.
